.. change::
    :tags: bug, orm
    :tickets: 10459

    Fixed issue where calling :meth:`_engine.Result.unique` with a new-style
    :func:`.select` query in the ORM, where one or more columns yields values
    that are of "unknown hashability", typically when using JSON functions like
    ``func.json_build_object()`` without providing a type, would fail
    internally when the returned values were not actually hashable. The
    behavior is repaired to test the objects as they are received for
    hashability in this case, raising an informative error message if not. Note
    that for values of "known unhashability", such as when the :class:`.JSON`
    or :class:`.ARRAY` types are used directly, an informative error message
    was already raised.

    The "hashabiltiy testing" fix here is applied to legacy :class:`.Query` as
    well, however in the legacy case, :meth:`_engine.Result.unique` is used for
    nearly all queries, so no new warning is emitted here; the legacy behavior
    of falling back to using ``id()`` in this case is maintained, with the
    improvement that an unknown type that turns out to be hashable will now be
    uniqufied, whereas previously it would not.
